language: scala

scala:
  - 2.11.7

jdk:
  # - openjdk7
  - oraclejdk7
  - oraclejdk8

script: travis_retry sbt ++$TRAVIS_SCALA_VERSION clean test


after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sbt docker:stage
  - docker build -t divanvisagie/SwissGuard server/target/docker/stage
  - docker push divanvisagie/SwissGuard
