version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=swissguard
    ports:
      - "1337:5432"
